framework:
    messenger:
        transports:
            publisher:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: interinvest_messages
                        type: topic


            # https://symfony.com/doc/current/messenger.html#transport-configuration
            consumer:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Core\Events\Serializer\MessageSerializer
                options:
                    # Désactiver la création d'une file d'attente par défaut (step queue à false)
                    auto_setup: false
                    exchange:
                        name: interinvest_messages
                        type: topic
                    queues:
                        ii_workflow:
                            binding_keys: ['*']

        default_bus: event.bus

        buses:
            event.bus:
                default_middleware: allow_no_handlers

        routing:
            App\Core\Events\Shared\Event\EventOutInterface: publisher
            App\Core\Events\Shared\Event\EventInInterface: consumer

