
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/srv/app/:rw,delegated
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/symfony.ini
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/key.pem:/etc/nginx/ssl/key.pem:ro
      - ./docker/nginx/cert.pem:/etc/nginx/ssl/cert.pem:ro

    environment:
      - APP_ENV=${APP_ENV:-dev}
      - SERVER_NAME=${DOMAIN}
    networks:
      default:
        aliases:
          - ${DOMAIN}


###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
